# Generated by Django 2.1 on 2018-08-30 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_playlist', '0004_song_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='user',
        ),
    ]
