# Generated by Django 2.1 on 2018-09-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_playlist', '0007_auto_20180901_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='id',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
